---
title: "Problem 4"
output: html_document
---

## Setup

```{r}
install.packages("hdm")
install.packages("AER")
install.packages("randomForest")
install.packages("lfe")
install.packages("glmnet")
```


```{r}
library(hdm)
library(AER) # applied econometrics library
library(randomForest) # random Forest library
library(lfe) # high-dimensional econometrics library
library(glmnet) # glm net
library(xtable)

set.seed(14383)
```


## Double ML function

```{r}
# DML for PLIVM
dml2_for_plivm <- function(x, d, z, y, dreg, yreg, zreg, nfold = 5) {
  # this implements DML2 algorithm, where there moments are estimated via DML, before constructing
  # the pooled estimate of theta randomly split data into folds
  
  # split into folds for cross-validation
  nobs <- nrow(x)
  foldid <- rep.int(1:nfold, times = ceiling(nobs / nfold))[sample.int(nobs)]
  I <- split(1:nobs, foldid)
  
  # create residualized objects to fill (the tilde variables)
  ytil <- dtil <- ztil <- rep(NA, nobs)
  
  # obtain cross-fitted residuals
  cat("fold: ")
  for (b in seq_along(I)) {
    
    # run the provided model to estimate the D,Z,Y regressions
    dfit <- dreg(x[-I[[b]], ], d[-I[[b]]]) # take the current fold out
    zfit <- zreg(x[-I[[b]], ], z[-I[[b]]]) # take the current fold out
    yfit <- yreg(x[-I[[b]], ], y[-I[[b]]]) # take the current folot out
    
    # fitted values for the current fold
    dhat <- predict(dfit, x[I[[b]], ], type = "response") # predict the fold out
    zhat <- predict(zfit, x[I[[b]], ], type = "response") # predict the fold out
    yhat <- predict(yfit, x[I[[b]], ], type = "response") # predict the fold out
    
   # residual values for the current fold
    dtil[I[[b]]] <- (d[I[[b]]] - dhat) # record residual
    ztil[I[[b]]] <- (z[I[[b]]] - zhat) # record residual
    ytil[I[[b]]] <- (y[I[[b]]] - yhat) # record residial
    cat(b, " ")
  }
  
  # fit a standard IV on the residualized data (no longer need covariates X)
  ivfit <- tsls(y = ytil, d = dtil, x = NULL, z = ztil, intercept = FALSE)
  coef_est <- ivfit$coef # extract coefficient
  se <- ivfit$se # record standard error
  cat(sprintf("\ncoef (se) = %g (%g)\n", coef_est, se))
  
  
  return(list(coef_est = coef_est, se = se, dtil = dtil, ytil = ytil, ztil = ztil))
}
```

## AJR Empirical example

```{r}
# Load AJR data
file <- "https://raw.githubusercontent.com/CausalAIBook/MetricsMLNotebooks/main/data/AJR.csv"
AJR <- read.csv(file)
dim(AJR)
```

```{r}
y <- AJR$GDP
d <- AJR$Exprop
z <- AJR$logMort

# raw covariates (5 dimensions)
xraw <- model.matrix(~ Latitude + Africa + Asia + Namer + Samer, data = AJR)

# rich set of covariates with interactions (21 dimensions)
x <- model.matrix(~ -1 + (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)
dim(x)
```

```{r}
set.seed(14383)
# DML with PostLasso
cat(sprintf("\n DML with Post-Lasso \n"))

dreg <- function(x, d) {
  hdm::rlasso(x, d)
} # ML method=lasso
yreg <- function(x, y) {
  hdm::rlasso(x, y)
} # ML method=lasso
zreg <- function(x, z) {
  hdm::rlasso(x, z)
} # ML method=lasso

dml2_lasso <- dml2_for_plivm(x, d, z, y, dreg, yreg, zreg, nfold = 5)


# DML with Random Forest
cat(sprintf("\n DML with Random Forest \n"))

dreg <- function(x, d) {
  randomForest(x, d)
} # ML method=Forest
yreg <- function(x, y) {
  randomForest(x, y)
} # ML method=Forest
zreg <- function(x, z) {
  randomForest(x, z)
} # ML method=Forest

dml2_rf <- dml2_for_plivm(xraw, d, z, y, dreg, yreg, zreg, nfold = 5)

# Compare Forest vs Lasso
comp_tab <- matrix(NA, 3, 2)
comp_tab[1, ] <- c(sqrt(mean((dml2_rf$ytil)^2)), sqrt(mean((dml2_lasso$ytil)^2)))
comp_tab[2, ] <- c(sqrt(mean((dml2_rf$dtil)^2)), sqrt(mean((dml2_lasso$dtil)^2)))
comp_tab[3, ] <- c(sqrt(mean((dml2_rf$ztil)^2)), sqrt(mean((dml2_lasso$ztil)^2)))
rownames(comp_tab) <- c("RMSE for Y:", "RMSE for D:", "RMSE for Z:")
colnames(comp_tab) <- c("RF", "LASSO")
rmse_comparison = xtable(comp_tab, digits = 3)
print(rmse_comparison, file = "rmse_comparison.tex", include.rownames = TRUE)
```

## Weak instruments

```{r}
# using lfe package
summary(felm(dml2_lasso$dtil ~ dml2_lasso$ztil), robust = TRUE)
summary(felm(dml2_rf$dtil ~ dml2_rf$ztil), robust = TRUE)
```

```{r}
# DML-AR (DML with Anderson-Rubin)

dml_ar_pliv <- function(rY, rD, rZ, grid,
                        alpha = 0.05,
                        save = FALSE,
                        filename = "") {

  if (save) {
    png(filename, width = 800, height = 600)
    on.exit(dev.off(), add = TRUE)
  }

  n <- length(rY)

  Cstat <- sapply(grid, function(g) {
    n * (mean((rY - g * rD) * rZ))^2 /
      var((rY - g * rD) * rZ)
  })

  crit <- qchisq(1 - alpha, 1)

  LB <- min(grid[Cstat < crit])
  UB <- max(grid[Cstat < crit])

  plot(
    grid, Cstat,
    type = "l",
    xlab = "Effect of institutions",
    ylab = "Statistic",
    main = " "
  )

  abline(h = crit, lty = 3, col = 4)
  abline(v = LB, lty = 3, col = 2)
  abline(v = UB, lty = 3, col = 2)

  invisible(list(LB = LB, UB = UB))
}
```


```{r}
dml_ar_pliv(
  rY = dml2_lasso$ytil, rD = dml2_lasso$dtil, rZ = dml2_lasso$ztil,
  grid = seq(-2, 2, by = .01), alpha = 0.05,
                        save = TRUE,
                        filename = "lasso_ar_plot.png"
)

dml_ar_pliv(
  rY = dml2_rf$ytil, rD = dml2_rf$dtil, rZ = dml2_rf$ztil,
  grid = seq(-2, 2, by = .01),alpha = 0.05,
                        save = TRUE,
                        filename = "rf_ar_plot.png"
)
```

